name: pre-commit-checks

# Doc: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Allow this workflow to be manually triggered
  workflow_dispatch:

jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    steps:
      # Doc: https://github.com/marketplace/actions/checkout
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      # Doc: https://github.com/marketplace/actions/setup-python
      - name: Setup Python
        uses: actions/setup-python@v4

      # Install pre-commit
      - name: Install pre-commit
        run: pip install pre-commit

      # Run pre-commit checks
      - name: Run pre-commit checks
        run: pre-commit run --all-files
